runMode: debug
swagger: false
log:
  level: debug
http:
  addr: ":8000"
  certFile: ""
  keyFile: ""
  shutdownTimeout: 30
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  dbName: user
  parameters: charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true
  maxLifetime: 7200
  maxOpenConns: 100
  maxIdleConns: 20
monitor:
  enable: true
  addr: ":6060"
  configDir: ""