// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOjLanguage = "oj_language"

// OjLanguage mapped from table <oj_language>
type OjLanguage struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name             string    `gorm:"column:name;type:varchar(50);not null" json:"name"`                    // 语言名称
	CompileStatement string    `gorm:"column:compile_statement;type:text;not null" json:"compile_statement"` // 编译语句
	CreateTime       time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime       time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName OjLanguage's table name
func (*OjLanguage) TableName() string {
	return TableNameOjLanguage
}
