// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOjStandardIo = "oj_standard_io"

// OjStandardIo mapped from table <oj_standard_io>
type OjStandardIo struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Input      string    `gorm:"column:input;type:text;not null" json:"input"`    // 输入
	Output     string    `gorm:"column:output;type:text;not null" json:"output"`  // 输出
	ProblemID  *int64    `gorm:"column:problem_id;type:bigint" json:"problem_id"` // 所属题目
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName OjStandardIo's table name
func (*OjStandardIo) TableName() string {
	return TableNameOjStandardIo
}
